// Downloads the two typefaces and writes src/fonts.css with the woff2 files
// embedded as data URIs, so the built page makes no request to Google and
// renders identically offline. Run once; the generated CSS is committed.
//
//   node tools/fetch-fonts.mjs
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const here = dirname(fileURLToPath(import.meta.url));

// A modern browser UA so the CSS comes back referencing woff2 rather than ttf.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

const FAMILIES = [
  "Chivo:wght@400;500;700;900",
  "Chivo+Mono:wght@400;600",
];

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join("&")}&display=swap`;

const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

// Keep the latin block only. The rest of the subsets triple the size for
// characters this interface never shows.
const blocks = css.split("/*").filter((block) => block.startsWith(" latin "));
if (blocks.length === 0) throw new Error("no latin subsets found in the Google Fonts response");

let out = `/* Generated by tools/fetch-fonts.mjs — do not edit by hand.
   Chivo and Chivo Mono, latin subset, embedded so the single-file build makes
   no external request and looks the same offline. Both are OFL licensed. */\n\n`;

let count = 0;
for (const block of blocks) {
  const body = "/*" + block;
  const href = /src:\s*url\((https:[^)]+\.woff2)\)/.exec(body);
  if (!href) continue;
  const bytes = Buffer.from(await (await fetch(href[1])).arrayBuffer());
  const face = body
    .slice(body.indexOf("@font-face"))
    .replace(/url\(https:[^)]+\.woff2\)/, `url(data:font/woff2;base64,${bytes.toString("base64")})`);
  out += face.trim().replace(/\n\s*/g, "\n  ") + "\n\n";
  count++;
}

if (count === 0) throw new Error("no @font-face rules were embedded");

writeFileSync(resolve(here, "../src/fonts.css"), out);
console.log(`embedded ${count} faces → src/fonts.css (${(out.length / 1024).toFixed(0)} kB)`);
